const projectsTypes = {
  ADD_PROJECT: "ADD_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  GET_PROJECTS: "GET_PROJECTS",
  GET_PROJECT: "GET_PROJECT",
  ADD_MEMBERS: "ADD_MEMBERS",
  EDIT_MEMBER: "EDIT_MEMBER",
  DELETE_MEMBER: "DELETE_MEMBER",
  GET_MEMBERS: "GET_MEMBERS",
};

export default projectsTypes;
