const tasksTypes = {
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  GET_TASKS: "GET_TASKS",
  GET_TASK: "GET_TASK",
  GET_COMMENTS: "GET_COMMENTS",
  COMMENT_TASK: "COMMENT_TASK",
  CLEAN_UP_TASKS: "CLEAN_UP_TASKS",
  EDIT_TASK_FIELD: "EDIT_TASK_FIELD"
};
  
  export default tasksTypes;